# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20180607_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.AddField(
            model_name='survey',
            name='video',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='survey.Video', verbose_name='Video'),
        ),
    ]
