# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20180607_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='video',
        ),
    ]
