# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_remove_survey_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.CharField(blank=True, max_length=50, verbose_name='Video ID'),
        ),
    ]
