# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_response_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='randomize_questions',
            field=models.BooleanField(default=True, verbose_name='Whether to randomize question to prevent bias'),
        ),
    ]
