# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_survey_randomize_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated time')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='video_cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='survey.VideoCategory'),
        ),
        migrations.AddField(
            model_name='video',
            name='cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='survey.VideoCategory'),
        ),
    ]
