# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20180607_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='video_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.VideoCategory'),
        ),
        migrations.AlterField(
            model_name='video',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.VideoCategory'),
        ),
    ]
