# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20180609_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='end',
            field=models.IntegerField(default=0, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='video',
            name='start',
            field=models.IntegerField(default=0, verbose_name='Start time'),
        ),
    ]
