# Generated by Django 2.1.2 on 2018-10-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_translated_name_for_models'),
        ('survey', '0018_auto_20180610_0007'),
    ]

    operations = [
    ]
